Repository media-service-dev/console, pull requests merged in 2020-03, with the labels that each got.

#3 Fix disappearing messages in createBlock
  src/Style/StyledOutput.ts
Labels: bug

#4 Remove version from readme
  README.md
Labels: chore, documentation

#5 Fix publish workflow
  .github/workflows/publish.yml
Labels: bug, chore

#6 Update dependencies
  package.json
  yarn.lock
Labels: chore, dependencies

#7 Fix shell expansion in scripts for eslint
  .github/workflows/build.yml
  .github/workflows/publish.yml
  package.json
Labels: bug, chore
